name: open_local_ui
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
repository: 'github.com/WilliamKarolDiCioccio/open_local_ui'

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  unicons: ^2.1.1
  logger: ^2.2.0
  adaptive_theme: ^3.6.0
  url_launcher: ^6.2.6
  langchain: ^0.5.0+1
  langchain_ollama: ^0.1.0
  flutter_markdown: ^0.7.0
  flutter_native_splash: ^2.4.0
  bitsdojo_window: ^0.1.6
  process_run: ^0.14.2
  http: ^1.2.1
  provider: ^6.1.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
